# Generated by Django 4.2 on 2023-06-13 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenhouseEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Событие теплицы',
                'verbose_name_plural': 'События теплицы',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.IntegerField()),
                ('plant_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimal_temperature', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plant')),
            ],
            options={
                'verbose_name': 'Температура',
                'verbose_name_plural': 'Температура',
            },
        ),
        migrations.CreateModel(
            name='PlantCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_instructions', models.TextField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plant')),
            ],
            options={
                'verbose_name': 'Уход за растением',
                'verbose_name_plural': 'Уход за растениями',
            },
        ),
        migrations.CreateModel(
            name='InGreenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'То что сейчас в теплице растет',
                'verbose_name_plural': 'То что сейчас в теплице растет',
            },
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatible_with', models.ManyToManyField(related_name='compatible_plants', to='myapp.plant')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='myapp.plant')),
            ],
            options={
                'verbose_name': 'Таблица совместимости',
                'verbose_name_plural': 'Таблицы совместимости',
            },
        ),
    ]
