# Generated by Django 4.2 on 2023-06-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_greenhouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greenhouse',
            options={'verbose_name': 'Размеры теплицы', 'verbose_name_plural': 'Размеры теплицы'},
        ),
    ]
