# Generated by Django 4.2 on 2023-06-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_greenhouse_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='cell',
            new_name='time',
        ),
    ]
