# Generated by Django 4.2 on 2023-06-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_planttype_delete_greenhouseevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
