# Generated by Django 4.2 on 2023-06-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ingreenhouse_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreenhouse',
            name='cell',
            field=models.CharField(max_length=255),
        ),
    ]
