# Generated by Django 4.2 on 2023-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_ingreenhouse_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreenhouse',
            name='planting_date',
            field=models.DateTimeField(),
        ),
    ]
