# Generated by Django 4.2 on 2023-06-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_ingreenhouse_planting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibility',
            name='incompatible_with',
            field=models.ManyToManyField(blank=True, related_name='incompatible_plants', to='myapp.plant'),
        ),
        migrations.AlterField(
            model_name='compatibility',
            name='compatible_with',
            field=models.ManyToManyField(blank=True, related_name='compatible_plants', to='myapp.plant'),
        ),
    ]
